travis:
  secure:
    BINSTAR_TOKEN: wkMZGswziqCaLWNYnzjPCbeeC9icvzsWOL7eVliasNyFIVJMvFayD9WufO5anyzSG4Y/cwSkQeGGZ8NozH6LUdpFSD0HhVz/igOr8fe/3GlmPzP1hSaorq2bERGNGYSU0rRyyt7ovA3jPlhNP6hEikrC0jQSFQrWCYtY7J3bSz1GeF43dyeRtCsIxk7muhHRyl1znodlIrEDumqdeDx3jR7nDgL5HPYqx/VwmIGbXCR5e3423kHkFuizFZjVbValO1Q4OXd7TNuszzSzo9HX6qRBRhSHZO37ps2X49wIj0gwfAKgQPRigbVWzB13RLY9PgGBwfuwKctunuG7J4BFqBsCafdODzwjSk+YX51t6Djc/Hq88b7LgVf0pU8HWi8J+Am/Y/9d7u7RTkVKeOg0IlJcEw5vWP0NEvvwBmFAx33sxUNpmxH79DsYiKKe7HZk/JSDzeUie59L9RkneOORieJfSSxk6qUPUNpXe3FxqN5u8SyRm8XqnFi8U7q4/cbiq2t9AaPF+9HmrWvo4qA6fWDCGnHs7iQRFzoFFQiyxXwU02aDXFzxEqU6vfgapJFQgA8hS5tZS8QvYvmSmuF0A8SL2RFz18uEBvlNp0WT9asxPVd/JhiC3SFoSKGt4gDifkP6JSYQv6CdrQw4NBC9Sdvfn5LaqK44xB/eOvEkkmo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
