travis:
  secure:
    BINSTAR_TOKEN: qujQTVcPGtWuW3ZzmP4ZeK97jl4GBlZk9/PVqhKteKrZDQmKpsDRp7LIvj2I2sZ4Z8sANOq8IIHI2lC/Z7DZQsJYf2+y1wOexNkDRghb6Xb4zz92+KWz5FwnRY3RYANtZCJJXKJcDhLJdhBppG6U5axvjyVO09I5zTEHcaRsJuhn79bnG4ZH7KDucnhQ54C96Pk9AFc6oPxF2Seg4JPfJMrsLBYCFykNhjIvWJw1K42mCJYqOGvuCZ/s3SabNwe8mA3kLSgfQ+9woJl32fkSarffG9TVQpBZcETJK7trs8TdY9qTgxKYouFrdRnAnXGIXCgiMmQM1CqQelyM8i0sOPnPLmI5oNsY0X+/w+UYOzPQhcLkrwnSIi4t+5GkqJiJyhuQP0nh2ypGgcKQsL9VjLqrvZJJzZxj8kFnkWV+M5Te+KETOVU4NKqRf55xSCY/uXBfBGo9UlxbHH8pQfSvJ92+J3SSdxsdzmr5pc1noLs6TV021M+S82tgW3C7fYqplIEVEXlWhTtHz/whmvMtR+uQ3X1OG5x4/A0rQDrsBfXpJtvPzbXupZg2aArCzMBQmDowdjEgJbLjZw4KdDN272MrSnJl02db0QWOqFk4sySCyetRIOcsw72SM0PdH24nKj/z5c9NHYv5EIyL1kILOxDvA/YDthALJCCddCEyvPg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
